// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"log"
)

// Injectors from wire.go:

func InitApplication(path string) *application {
	mainConfig := newConfig(path)
	mainDb := newDB(mainConfig)
	mainApplication := newApplication(mainConfig, mainDb)
	return mainApplication
}

// wire.go:

func newConfig(path string) *config {

	dbAddr := "localhost:6379"

	return &config{
		dbAddr: dbAddr,
	}
}

func newDB(config2 *config) *db {
	log.Println("connection db: " + config2.dbAddr)
	return &db{}
}

func newApplication(config2 *config, db2 *db) *application {
	return &application{
		config: config2,
		db:     db2,
	}
}
