// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/miiy/go-examples/pkg/wire/demo1/config"
	"github.com/miiy/go-examples/pkg/wire/demo1/db"
	"github.com/miiy/go-examples/pkg/wire/demo1/service"
	"github.com/miiy/go-examples/pkg/wire/demo1/store"
)

// Injectors from wire.go:

func initUserService(conf string) (*service.UserService, error) {
	configConfig := config.NewDefaultConfig(conf)
	sqlDB, err := db.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	userStore, err := store.NewUserStore(configConfig, sqlDB)
	if err != nil {
		return nil, err
	}
	userService, err := service.NewUserService(userStore)
	if err != nil {
		return nil, err
	}
	return userService, nil
}
